### ISSUE TITLE
List of open source editors with "out-of-the-box" Julia support

### ISSUE THREAD

**Issue by s-celles** [JuliaEditorSupport/roadmap#11]
Maybe we should have a list of open source editors with "out-of-the-box" Julia support that are not listed in https://github.com/JuliaEditorSupport/ projects.

I was very pleased to see that [micro](https://micro-editor.github.io/), a modern and intuitive terminal-based text editor have Julia support

[ne](http://ne.di.unimi.it/) (nice editor, an other console editor) currently doesn't have an "out-of-the-box" Julia support but [I hope we can expect one](https://groups.google.com/forum/#!topic/niceeditor/N9RJBlvJTVk).

**Comment by oxinabox** [comment]
Yes,
would it fit in the  Readme for
https://github.com/JuliaEditorSupport/3rd-Party-Highlighters
