### ISSUE TITLE
Take ownership of twadleigh/julia-syntax-test-cases

### ISSUE THREAD

**Issue by twadleigh** [JuliaEditorSupport/roadmap#13]
I put together a little kernel of something potentially useful to this audience at https://github.com/twadleigh/julia-syntax-test-cases.

**Comment by s-celles** [comment]
This repository could be interesting for testing Julia support for various IDE.
You need to transfer ownership https://help.github.com/en/articles/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account

**Comment by twadleigh** [comment]
@scls19fr, I need to be given permission to create repositories in this group in order to do so.

**Comment by davidanthoff** [comment]
@twadleigh I've made you an owner of this org for now. Once the transfer is complete, please ping me and I'll make you a normal member of the org and give you admin access to your repo, if that sounds good to you!

**Comment by twadleigh** [comment]
@davidanthoff 	*ping*.

**Comment by s-celles** [comment]
https://github.com/JuliaEditorSupport/julia-syntax-test-cases

**Comment by s-celles** [comment]
@twadleigh I made you admin of https://github.com/JuliaEditorSupport/julia-syntax-test-cases but member (and not owner) of https://github.com/JuliaEditorSupport/ because I don't think that's necessary. Thanks for your contribution.

**Comment by davidanthoff** [comment]
Perfect!
