### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by femtotrader** [JuliaEditorSupport/roadmap#4]
New logo for JuliaEditorSupport was proposed
https://discourse.julialang.org/t/new-logo-for-julia-editor-support/3955

Pinging @oxinabox @jballanc @tkelman 

What is current status?

**Comment by oxinabox** [comment]
Oh yeah, sorry, I got busy with a paper.
Since that is now submitted, I'll finish that up in the next few hours.
Based on feedback in the thread, I'll make one up.
and put it in place.
And I'll commit the code to this repo/
And if anyone feels strongly, they can open an issue and change it

**Comment by jballanc** [comment]
:+1:

It didn't seem there was any objection to the overall theme of the proposed logo, more just discussion of some of the finer points. Probably best at this point to just put something up and push forward. Once we start seeing the logo used in different contexts at different sizes, we'll likely have a better feel for what works or doesn't work.

**Comment by oxinabox** [comment]
I used @jballanc's  ofsetting trick so as to get bolder text.
but I didn't change the color of the shadow, so it is just bold -- not shadowed.

It is on the white background. I'm still partial to the black, but matching github is a definite plus.

**Comment by sbromberger** [comment]
So, not to make TOO big a thing of this, but there's a typo in some of the text in the purple circle. Look for "signiture". :)

(Maybe that's intentional irony for an editor organization? :) )

**Comment by oxinabox** [comment]
i thought i fixed that when you pointed it out before. Maybe i made 2 mistakes

**Comment by sbromberger** [comment]
*I* didn't point it out before.... did someone else?

**Comment by oxinabox** [comment]
must have been

**Comment by oxinabox** [comment]
To cover future peoples bases:
I release the logo I created, as found at https://github.com/JuliaEditorSupport/roadmap/blob/be35116f493e770d4b8e6ca1285ac4a1e88290ad/logo.ipynb
under the CC0 No Rights Reserved License

https://creativecommons.org/share-your-work/public-domain/cc0/ 

Do with it as you will
