### ISSUE TITLE
Notepad++

### ISSUE THREAD

**Issue by s-celles** [JuliaEditorSupport/roadmap#5]
Hello,

a repository for Notepad++ should be created inside JuliaEditorSupport GitHub organization
See https://discourse.julialang.org/t/notepad-and-julia/1979 and
https://github.com/JuliaLang/julia/issues/22106

Kind regards

**Comment by s-celles** [comment]
Pinging  @yuyichao @tkelman @StefanKarpinski @DANA-Laboratory @JeffBezanson @simonbyrne @Sacha0 @nalimilan @nolta @cameyo42 @andyferris @ViralBShah @cameyo42
https://github.com/JuliaLang/julia/blob/master/contrib/Julia_Notepad%2B%2B.xml
https://github.com/JuliaLang/julia/blob/master/contrib/Notepad%2B%2B_2_Julia.ahk

**Comment by Sacha0** [comment]
Please avoid unnecessarily pinging parties like so. Best!

**Comment by ViralBShah** [comment]
Need to ping the owners here. I would have created it if I had access.

**Comment by StefanKarpinski** [comment]
I've invited @ViralBShah, @JeffBezanson and @KristofferC to be admins of this org.

**Comment by ViralBShah** [comment]
You invited me to the roadmap repo. I need to be admin  of the org to help here.

**Comment by s-celles** [comment]
Sorry @Sacha0 for noise, that's just a way to have all initial contributors to be informed and to speed things up given the fact that my discourse post was from february 2017

**Comment by ViralBShah** [comment]
https://github.com/JuliaEditorSupport/NotepadPlusPlus

@scls19fr Can you move the notepad++ files there?

**Comment by s-celles** [comment]
That's done in https://github.com/JuliaEditorSupport/NotepadPlusPlus/pull/1

**Comment by s-celles** [comment]
Reopening this issue because files [need to be removed from JuliaLang/julia/contrib](https://github.com/JuliaLang/julia/pull/24881) and a link need to be added to https://github.com/JuliaEditorSupport/NotepadPlusPlus or more generaly to https://github.com/JuliaEditorSupport/
