### ISSUE TITLE
ack / ag

### ISSUE THREAD

**Issue by s-celles** [JuliaEditorSupport/roadmap#6]
ack support should be move from base to https://github.com/JuliaEditorSupport/
see https://github.com/JuliaLang/julia/issues/22106

- [x] Create repository that belong to this org
- [x] Copy files from Julia contrib
- [x] Remove files from Julia contrib

ack-grep https://beyondgrep.com/install/
see also http://betterthanack.com/
  silversearcher-ag https://github.com/ggreer/the_silver_searcher

**Comment by s-celles** [comment]
Pinging @artnez

**Comment by s-celles** [comment]
Does it worth to move these 2 files?

https://github.com/JuliaLang/julia/blob/master/contrib/ackrc
https://github.com/JuliaLang/julia/blob/master/contrib/README.ackrc.txt

**Comment by ViralBShah** [comment]
Seems like a good idea to me.

**Comment by artnez** [comment]
@scls19fr Pong. What's up?

**Comment by s-celles** [comment]
We are currenlty moving Julia editor support from base (ie https://github.com/JuliaLang/julia/) to separate repositories belonging to https://github.com/JuliaEditorSupport/ GitHub organization.
https://github.com/JuliaLang/julia/blob/master/contrib/ackrc is only 2 rows length, so I wondered if we really should move this file also.
I personaly don't use ack / ag / ... (and never heard of before)
Could you explain here how to use this file so we could add a README.md to explain what can be done with this configuration file.
Kind regards

**Comment by artnez** [comment]
Ah, I forgot about this commit :) Ack supports an `.ackrc` configuration file that let's you teach it how to detect file types. That configuration file allows you to filter your search by Julia files only.

```
$ ack --julia ...
```

**Comment by ViralBShah** [comment]
Should we still move `ack` out of Julia contrib? It was refactored a bit in: https://github.com/JuliaLang/julia/commit/2d8c1ecd532405ab6872dd5cdcef0be3f26e6c14

**Comment by s-celles** [comment]
`ackrc` file for Ack is available now at https://github.com/JuliaEditorSupport/julia-ack
