### ISSUE TITLE
GtkSourceView

### ISSUE THREAD

**Issue by s-celles** [JuliaEditorSupport/roadmap#9]
GtkSourceView support should be move from base to https://github.com/JuliaEditorSupport/
see https://github.com/JuliaLang/julia/issues/22106

- [x] Create repository that belong to this org
- [x] Copy files from Julia contrib
- [x] Remove files from Julia contrib

**Comment by s-celles** [comment]
Pinging @tkelman @waldyrious @nolta @JeffBezanson @StefanKarpinski @joeltay @simonbyrne @nalimilan @kmsquire @jakebolewski @ararslan @andyferris 
https://github.com/JuliaLang/julia/blob/master/contrib/julia.lang

**Comment by StefanKarpinski** [comment]
This is a good idea but please don't ping everyone like this.

**Comment by s-celles** [comment]
Julia support for GtkSourceView is now available at https://github.com/JuliaEditorSupport/julia-GtkSourceView

https://github.com/JuliaLang/julia/pull/24893 remove it from Julia base
